# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

aliases:
  - &filter-non-gh-pages
      branches:
        ignore:
          - gh-pages

version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install
          command: |
            sudo apt-get install libusb-1.0-0-dev
            yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Syntax Lint
          command: yarn lint:ci
      - run:
          name: Test
          command: yarn test
      - persist_to_workspace:
          # relative to working_directory
          root: "./"
          paths:
            - "./"

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters: *filter-non-gh-pages
